### ISSUE TITLE
你好，请问有后续内存池等的代码嘛

### ISSUE THREAD

**Issue by Justhuayu** [Magge-Lin/ggsddu#1]
作者你好，请问有内存池这些的代码嘛，我是看零声的课程，没找到代码，不知道你有没有

**Comment by Magge-Lin** [comment]
传上去了，在ggsddu\tools\mem_pool\src目录.


发件人: ***@***.***>
发送时间: 2024年3月20日 20:39
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Magge-Lin/ggsddu] 你好，请问有后续内存池等的代码嘛 (Issue #1)


作者你好，请问有内存池这些的代码嘛，我是看零声的课程，没找到代码，不知道你有没有

―

**Comment by Justhuayu** [comment]
感谢🙏

**Comment by Justhuayu** [comment]
你好，请问你有这个课程的对应资料没呢，可以有偿分享下嘛
